version: "3.9"

volumes:
    php-fpm-socket:
    psysh-store:

services:
  app:
    build:
      context: .
      dockerfile: ../test1/php/Dockerfile
    volumes:
      - type: bind
        source: ./src
        target: /src
      - type: volume
        source: php-fpm-socket
        target: /var/run/php-fpm
        volume:
          nocopy: true
      - type: volume
        source: psysh-store
        target: /root/.config/psysh
        volume:
          nocopy: true
  # |--------------------------
  # |
  # | ここから追記
  # |
  # |--------------------------
  web:
    build:
      context: .
      dockerfile: ../test1/nginx/Dockerfile
    ports:
      - target: 80
        protocol: tcp
        mode: host
        published: 80
    volumes:
      - type: bind
        source: ./src
        target: /src
      - type: volume
        source: php-fpm-socket
        target: /var/run/php-fpm
        volume:
          nocopy: true
